services:
  - type: web
    name: chess-server
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start # server/package.json の scripts.start を参照
    envVars:
      - key: NODE_VERSION
        value: 18
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: chess-db
      #     property: connectionString

  - type: static
    name: chess-client
    plan: free
    region: oregon
    rootDir: client
    buildCommand: npm install && npm run build # client/package.json の scripts.build を参照
    publishDir: dist # Viteのデフォルトビルド出力先
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION # ビルド時にNode.jsが必要な場合
        value: 18
      - key: VITE_API_URL # フロントエンドからバックエンドAPIを参照する場合の例
        fromService:
          type: web
          name: chess-server # 上記のバックエンドサービス名
          envVarKey: RENDER_EXTERNAL_URL # Renderが提供する外部URL