# render.yaml の client サービス部分の例
- type: static
  name: chess-client
  # ... (他の設定) ...
  envVars:
    - key: VITE_SOCKET_URL # Viteの場合、import.meta.env.VITE_SOCKET_URLで参照
      fromService:
        type: web
        name: chess-server # バックエンドサービス名
        envVarKey: RENDER_EXTERNAL_URL # Renderが提供する外部URL